### ISSUE TITLE
[SidebarLinks] Verlinkung von Gliederungspunkten und Beiträgen aus dem Inhaltsverzeichnis

### ISSUE THREAD

**Issue by aldur15** [Rusi91/basisdokument#10]
Als Nutzer möchte ich Verweise auf die Gliederungspunkte und Beiträge innerhalb des Inhaltsverzeichnisses haben, damit ich schneller darauf zugreifen kann.

Akzeptanzkriterien:
- [x]  Gliederungspunkte und Beiträge sollen anklickbar sein.
- [x]  Links sollten auf das zugehörige Element verweisen und es entsprechend anzeigen.

**Comment by silvia-ivanova-github-rep** [comment]
Schließen nach dem Review.
