### ISSUE TITLE
[Posts] Lineare Beitragsansicht

### ISSUE THREAD

**Issue by aldur15** [Rusi91/basisdokument#11]
Als Nutzer möchte ich Beiträge in einem horizontalen Verlauf lesen können.

Akzeptanzkriterien:
 - [x] Gliederungspunkte sind sichtbar
 - [x] Beiträge sind diesen untergeordnet
 - [x] In Beiträgen ist feste Textform (Autor und Zeit stehen am Anfang, danach der Beitragsinhalt)
 - [x] Keine Funktionalität, um neue Beträge hinzuzufügen
 - [x] Erstmal kein Markdownsupport nötig

![Image](https://user-images.githubusercontent.com/18146212/186139673-4c73c806-6a2b-4197-8c22-e0ade149be26.png)

**Comment by MaximilianHuber** [comment]
Alles implementiert, im Branch gepushed, noch nicht gepulled, da ich noch weiter dran arbeite
