### ISSUE TITLE
[Editor] Editor zum Erstellen von Beiträgen, Notizen, Hinweisen

### ISSUE THREAD

**Issue by MaximilianHuber** [Rusi91/basisdokument#12]
Als Nutzer:in möchte ich einen Editor haben, damit ich Beiträge, Notizen, Hinweisen zu meinen Beiträgen erstellen kann.

**Akzeptanzkriterium**

- [x] Button zum Erstellen von Gliederungspunkten, Beiträgen und Notizen.
- [x] Formatierungsmöglichkeiten sollen existieren
- [x] Sollte Markdown produzieren
- [x] Dafür notwendige Daten sollen herausgelesen werden (aktueller Nutzer, Datum, usw.)
- [x] Editor muss alle Eingabemöglichkeiten (Titel, Nachricht, usw.) bieten.

**Comment by MaximilianHuber** [comment]
Editor als art Popup, das der nicht dauernd da ist

**Comment by Rusi91** [comment]
Bezüglich Notizen/Hinweise und Beiträgen reicht der aktuelle Editor aus.

Bezüglich Gliederungspunkt fehlt die Eingabe von Titeln im Editor.

**Comment by silvia-ivanova-github-rep** [comment]
Schließen nach dem Review.
