### ISSUE TITLE
[Content] Editor zum Erstellen von neuen Überschriften/Absätzen unabhängig von Parteien

### ISSUE THREAD

**Issue by MaximilianHuber** [Rusi91/basisdokument#13]
_Als Nutzer:in möchte ich einen Texteditor haben, um damit Überschriften und Absätze erstellen und hinzufügen zu können._ 

Abhängigkeiten:
 - #11

**Comment by silvia-ivanova-github-rep** [comment]
Schließen nach dem Review.
