### ISSUE TITLE
[SidebarLinks] Erstellen eines Table-of-Contents/Inhaltsverzeichnis

### ISSUE THREAD

**Issue by MaximilianHuber** [Rusi91/basisdokument#14]
_Als Nutzer:in möchte ich ein Inhaltsverzeichnis für einzelne Gliederungspunkte, damit auf diese Gliederungspunkte verwiesen werden kann. 
Als Nutzer:in möchte ich ein Inhaltsverzeichnis für einzelne Beiträge, damit auf diese Beiträge verwiesen werden kann. 
Als Nutzer:in möchte ich eine Nummerierung für einzelne Gliederungspunkte und damit zusammenhängende Beiträge, damit auf diese verwiesen werden kann._ 

Abhängigkeiten:
 - #11 

- [x] Erweiterbare Liste implementieren
- [x] Erstellte Gliederungspunkte sollen der Liste automatisch hinzugefügt werden (Logik bereitstellen)
- [x] Erstellte Titel der Beiträge sollen der Liste automatisch hinzugefügt werden (Logik bereitstellen)
- [x] Nummerierung/Reihenfolge soll stimmen

![Image](https://user-images.githubusercontent.com/41992838/186141432-05043bb6-a5b2-44cc-bf16-8f9de2f4e1e6.jpg)

**Comment by silvia-ivanova-github-rep** [comment]
Schließen nach dem Review.
