### ISSUE TITLE
[Content] Erstellen von einzelnen Beiträgen

### ISSUE THREAD

**Issue by MaximilianHuber** [Rusi91/basisdokument#15]
Als Nutzer:in möchte ich in den Gliederunspunkten die einzelnen Beiträge erstellen und bearbeiten können.

Abhängigkeiten:
 - #12 

Akzeptanzkriterien:

- [x] In den Gliederunspunkten neue Beiträge erstellen
- [x] Diese Beiträge bearbeiten

**Comment by silvia-ivanova-github-rep** [comment]
Schließen nach dem Review.
