### ISSUE TITLE
Regeln für die Benennung von Variablen definieren

### ISSUE THREAD

**Issue by MaximilianHuber** [Rusi91/basisdokument#16]

**Comment by silvia-ivanova-github-rep** [comment]
Empfohlene Methode zum Deklarieren von JavaScript-Variablen und Funktionen ist die Verwendung von Camel-Case-Variablennamen.
Beispiel:
`function myFunction(firstParameter, secondParameter) { 
  return '${firstParameter} ${secondParameter}';
}`

Konstanten sollten in Großbuchstaben geschrieben werden, da sie sich nicht ändernde Variablen sind.
Beispiel:
`const PI = 3.141592653589793;
`

Klassennamen sollten in Pascal-Schreibweise geschrieben werden.
Beispiel:
`class MyClass{...}`

Komponenten sollten in Pascal-Schreibweise geschrieben werden.
Beispiel:
`MyComponentName`

Quelle: [https://www.syncfusion.com/blogs/post/10-javascript-naming-conventions-every-developer-should-know.aspx](url)
