### ISSUE TITLE
Textansicht mit Markdownsupport

### ISSUE THREAD

**Issue by Shoggomo** [Rusi91/basisdokument#21]
Ich als Nutzer:in möchte alle geschriebenen Texte mit korrekter Formatierung lesen können.

Diese Textansicht muss noch nicht in anderen Komponenten eingefügt werden. Es geht nur um die grundlegende Funktionalität.

Akzeptanzkriterien:
 - [x] Eine Komponente existiert, welcher Text im Markdown Format übergeben und die diese korrekt formatiert anzeigt.

**Comment by silvia-ivanova-github-rep** [comment]
Schließen nach dem Review.
