### ISSUE TITLE
Notizen- und Hinweisansicht

### ISSUE THREAD

**Issue by Shoggomo** [Rusi91/basisdokument#22]
Als Nutzer möchte ich Notizen und Hinweise in einem horizontalen Verlauf lesen können.

Akzeptanzkriterien:
 - [x] Notizen werden untereinander angezeigt
 - [x] Hinweise werden eingerückt mit „Richtersymbol“ im Hintergrund angezeigt
 - [x] Keine Funktionalität, um neue Notizen hinzuzufügen
 - [x] Erstmal kein Markdownsupport nötig

![Image](https://user-images.githubusercontent.com/18146212/186146808-0008020c-8b66-4bff-8c99-dacdd7b99f25.png)

**Comment by Rusi91** [comment]
![Image](https://user-images.githubusercontent.com/41992838/186503996-fd7ba964-f25a-4fcd-b567-74f79dc38e26.jpg)

**Comment by silvia-ivanova-github-rep** [comment]
Schließen nach dem Review.
