### ISSUE TITLE
Markdownsupport bei allen Textansichten

### ISSUE THREAD

**Issue by Shoggomo** [Rusi91/basisdokument#23]
Ich als Nutzer:in möchte alle geschriebenen Texte mit korrekter Formatierung lesen können.

Die bereits implementierte Markdownansicht soll in allen relevanten Stellen eingefügt werden.

Abhängigkeiten:
 - #21

Akzeptanzkriterien:
 - [x] Beiträge werden mit Markdownsupport angezeigt
 - [x] Notizen werden mit Markdownsupport angezeigt
 - [x] Hinweise werden mit Markdownsupport angezeigt

**Comment by silvia-ivanova-github-rep** [comment]
Schließen nach dem Review.
