### ISSUE TITLE
Json

### ISSUE THREAD

**Issue by MaximilianHuber** [Rusi91/basisdokument#29]
Sämtliche Dummy Daten sind in einer Json Datei gespeichert. Diese kann man im app.tsx auslesen und weitergeben. Mittels einer Methode kann man neue Daten an das Json hinzufügen. 

- [x] Datein in Json speichern
- [x] Daten auslesen könnnen
- [x] Neue Daten hinzufügen können

**Comment by MaximilianHuber** [comment]
Json auslese geht schon, einfach importieren mit:
import backendData from "../../backend.json";

dann kann man mittels backendData. einfach auslesen was man braucht

**Comment by silvia-ivanova-github-rep** [comment]
Schließen nach dem Review.
