### ISSUE TITLE
[Allgemein] JSON und LocalStorage Datenmanagement

### ISSUE THREAD

**Issue by Rusi91** [Rusi91/basisdokument#42]
Als Nutzer:in möchte ich dass meine erstellten Beiträge, Notizen, usw. abgespeichert und geladen werden, damit der aktuelle Stand nicht verloren geht.

- [x] Erweiterung der backend.json um Notizen bzw. Hinweise
- [x] Notizen sollen in den einzelnen Beiträgen als NoteData Array gespeichert werden
- [x] Zu Beginn sollen alle Gliederungspunkte, Beiträge und Notizen aus der JSON herausgelesen werden.
- [x] Abspeichern von neuen Gliederungspunkten, Beiträgen und Notizen im local storage.

**Comment by Rusi91** [comment]
_**Implementierung vom useLocalStorage:**_

_Import:_
import useLocalStorage from "../../hooks/useLocalStorage";

**Code Beispiel:**
const [currentUser, setCurrentUser] = useLocalStorage("currentUser", props.currentUser)

Dadurch können Daten im lokalen Speicher gespeichert werden, was dazu führt, dass die Daten selbst beim Neuladen der Seite bestehen bleiben. Cookies löschen um die Daten zu löschen. Es ist ein Lösungsansatz dafür, dass man mit react nicht in die JSON einzelne Daten reinschreiben kann. Mann kann jedoch ein JSON komplett überschreiben, was wir dann später mit dem "Download" Button machen.

**Comment by Rusi91** [comment]
### Ablauf:

1) Nutzer öffnet Anwendung -> Alle Daten (Gliederungspunkte, Beiträge und Notizen) werden aus dem JSON (backend.json) geladen.

2) Neue Gliederungspunkte, Beiträge und Notizen werden im lokalen Speicher gespeichert.

3) Beim "Download" werden alle Daten (aktuelle Gliederungspunkte, Beiträge und Notizen) im JSON überschrieben, wodurch das nächste mal beim Laden aus dem JSON die neuen Gliederungspunkte, Beiträge und Notizen dabei sind.

Mann könnte natürlich nach jedem neuen Gliederungspunkt, Beitrag oder Notiz die JSON automatisch überschreiben. Das sollten wir dann noch diskutieren.

**Comment by silvia-ivanova-github-rep** [comment]
Schließen nach dem Review.
