### ISSUE TITLE
Suchfunktion in Topbar

### ISSUE THREAD

**Issue by Leosssss** [Rusi91/basisdokument#48]
Als Nutzer:in möchte ich eine Suchfunktion für meine Gliederungspunkte und Beiträge haben, damit ich die Gliederungspunkte und Beiträge per Text finden kann.

Akzeptanzkriterien:

- [x] Nur relevante Gliederungspunkte anzeigen, die der Sucheingabe entsprechen
- [x] Nur relevante Beiträge anzeigen, die der Sucheingabe entsprechen

**Comment by Rusi91** [comment]
Vorschlag wie man es machen könnte:



![Image](https://user-images.githubusercontent.com/41992838/187737755-9fbe539d-3105-4ee0-bb21-5050d740713f.jpg)

**Comment by silvia-ivanova-github-rep** [comment]
Schließen nach dem Review.
