### ISSUE TITLE
Bug: Es wird nur einen Gliederungspunkt hinzugefügt

### ISSUE THREAD

**Issue by silvia-ivanova-github-rep** [Rusi91/basisdokument#52]
Es wird nur einen Gliederungspunkt hinzugefügt. Wenn ich einen zweiten Gliederungspunkt hinzufüge, dann wird dieser durch den letzten Gliederungspunkt ersetzt.

**Comment by Rusi91** [comment]
Bug wurde gefixt. Fehler lag darin, dass bei jedem neuen Gliederungspunkt die id = "3" war. Dadurch wurde der dritte Gliederungspunkt überschrieben. Problem war das die Länge vorher an der falschen Stelle abgefragt wurde.
