### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by Leosssss** [Rusi91/basisdokument#72]
Wenn Gliederungspunkt gelöscht werden, Notes werden nicht richtig platziert.

wenn man zb G1 löschen, Notes(zu G2 gehört) bleibt bei G3

**Comment by Leosssss** [comment]
partly solved

**Comment by Leosssss** [comment]
es hängt von der Gliederungspunkt ID auf, also könnte noch nicht gearbeitet werden

**Comment by Rusi91** [comment]
**Problem gelöst:**

Das Problem war, dass bei Löschungen die IDs nicht richtig neuverteilt wurden und auch nicht immer alle IDs.
Jetzt werden bei allen Löschungen alle IDs jedes Objekts neu verteilt.
