### ISSUE TITLE
[Beiträge] Referenz für Anlagen in Beiträgen hinterlegen

### ISSUE THREAD

**Issue by Rusi91** [Rusi91/basisdokument#84]
**Als Nutzer:in möchte ich Beweismittel in Beiträgen referenziert haben, damit immer klar ist auf welche Beweismittel sich bezogen wird.**

- [x] Bereich in jedem Beitrag einfügen, in dem Referenzen zu Beweismitteln (Strings; Namen der Beweismitteldateien) hinterlegt werden können.
- [x] Referenzen editierbar/löschbar
- [x] Checkboxen hinzufügen (für Richter später)

**Laut Projektmeeting 09.09.:**  Wir brauchen nur Referenzen (z.B. Kaufvertrag). Kein aktueller Ort (Ordner zum Aufbewahren von Beweismitteln nötig)

**Comment by silvia-ivanova-github-rep** [comment]
Schließen nach dem Review.
